name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore --runtime linux-x64
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish --no-restore --self-contained --runtime linux-x64 -o output
      - name: Strip
        run: strip output/SteamAuthTicket
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: output/SteamAuthTicket
