name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore --runtime linux-x64
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish --no-restore --self-contained --runtime linux-x64 -o output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: output/SteamAuthTicket
      - name: Make release
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: output/SteamAuthTicket
